### ISSUE TITLE
Title field for Pivot Tables

### ISSUE THREAD

**Issue by beatestermann** [cpvrlab/sparql-table-viewer#25]
Add a title field for Pivot Tables so that data fields that are uniform across the table can be dragged into the title field.

Example: http://yasgui.org/short/4J3fgHMhx
In this example, pollutantValue, aggregationValue, and unitValue should go into the title field and be displayed on top of the table.

**Comment by l00mi** [comment]
YasGui is another LinkedData Tool not related to this project. Here is there queue: https://github.com/OpenTriply/YASGUI/issues (They don't know about this Project, so you need to explain in more general terms.)

Probably you can achieve your goal manually by using "Google Charts" instead of "Pivot Table"?
